packages:
  - 'apps/*'
  - 'packages/*'
  - 'libs/*'
allowBuilds:
  '@swc/core': true
  esbuild: true
  nx: true
minimumReleaseAgeExclude:
  - '@typescript-eslint/tsconfig-utils@8.66.0'
  - '@typescript-eslint/types@8.66.0'
onlyBuiltDependencies:
  - '@swc/core'
  - 'esbuild'
  - 'nx'
